language: python
python:
  - '3.4'
sudo: false
env:
  global:
    - BUILD_SOC=1
    - secure: "DUk/Ihg8KbbzEgPF0qrHqlxU8e8eET9i/BtzNvFddIGX4HP/P2qz0nk3cVkmjuWhqJXSbC22RdKME9qqPzw6fJwJ6dpJ3OR6dDmSd7rewavq+niwxu52PVa+yK8mL4yf1terM7QQ5tIRf+yUL9qGKrZ2xyvEuRit6d4cFep43Ws="
before_install:
  - mkdir -p $HOME/.mlabs
  - if [ $TRAVIS_PULL_REQUEST != false ]; then BUILD_SOC=0; fi
  - if [ $BUILD_SOC -ne 0 ]; then ./.travis/get-xilinx.sh; fi
  - . ./.travis/get-toolchain.sh
  - . ./.travis/get-anaconda.sh
  - source $HOME/miniconda/bin/activate py34
  - conda install pip coverage binstar migen cython
  - pip install coveralls
install:
  - conda build conda/artiq
  - conda install artiq --use-local
script:
  - coverage run --source=artiq setup.py test
  - make -C doc/manual html
notifications:
  email: false
